apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-apis
spec:
  rules:
    - host: address.jailtonjunior.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: address-api
                port:
                  number: 80
    - host: partners.jailtonjunior.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: partner-api
                port:
                  number: 80
