apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: address-api
  name: address-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-api
  template:
    metadata:
      labels:
        app: address-api
    spec:
      containers:
        - name: address-api
          image: partnersregistry.azurecr.io/address:latest
          # livenessProbe:
          #   httpGet:
          #     port: 9000
          #     path: /health
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
          ports:
            - containerPort: 9000
