name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ADDRESS_API: address-api
  PARTNER_API: partner-api
  K8S_NAMESPACE: partner

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Variable Substitution (Address API)
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/address/settings.json
        env:
          geocode.key: ${{ secrets.GOOGLE_KEY }}

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push (Address API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: address/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_SERVER }}/${{ env.ADDRESS_API }}:latest
            ${{ secrets.ACR_SERVER }}/${{ env.ADDRESS_API }}:v${{ github.run_number }}

      - name: Variable Substitution (Partner API)
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/partner/settings.Production.json
        env:
          mongo.connectionString: ${{ secrets.COSMOS_CONNECTION }}

      - name: Build and push (Partner API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: partner/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_SERVER }}/${{ env.PARTNER_API }}:latest
            ${{ secrets.ACR_SERVER }}/${{ env.PARTNER_API }}:v${{ github.run_number }}

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Deploy Namespace
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            .k8s/namespaces/partner-ns.yaml        

      - name: Deploy Address API
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ secrets.ACR_SERVER }}/${{ env.ADDRESS_API }}:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/address-api-dp.yaml
            .k8s/services/address-api-svc.yaml

      - name: Deploy Partner API
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ secrets.ACR_SERVER }}/${{ env.PARTNER_API }}:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/partner-api-dp.yaml
            .k8s/services/partner-api-svc.yaml