name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ADDRESS_API: address-api
  PARTNER_API: partner-api
  RESOURCE_GROUP: go-challenge-rg

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Variable Substitution (Address API)
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/address/settings.json
        env:
          geocode.key: ${{ secrets.GOOGLE_KEY }}

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Address API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: address/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.ADDRESS_API }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.ADDRESS_API }}:v${{ github.run_number }}

      - name: Variable Substitution (Partner API)
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/partner/settings.Production.json
        env:
          mongo.connectionString: ${{ secrets.COSMOS_CONNECTION }}

      - name: Build and push (Partner API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: partner/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PARTNER_API }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PARTNER_API }}:v${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure Container Instances (Address API)"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.ADDRESS_API }}:v${{ github.run_number }}
          name: api-address-${{ github.run_number }}
          dns-name-label: api-address-${{ github.run_number }}
          location: East US

      # - name: "Deploy to Azure Container Instances (Partner API)"
      #   uses: "azure/aci-deploy@v1"
      #   with:
      #     resource-group: ${{ env.RESOURCE_GROUP }}
      #     image: ${{ secrets.DOCKER_USERNAME }}/${{ env.PARTNER_API }}:v${{ github.run_number }}
      #     name: api-partner
      #     dns-name-label: api-partner-${{ github.run_number }}
      #     location: East US
