name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ADDRESS_API: address-api
  PARTNER_API: partner-api

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/address/settings.json
        env:
          geocode.key: ${{ secrets.GOOGLE_KEY }}

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Address API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: address/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.ADDRESS_API }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.ADDRESS_API }}:v${{github.run_number}}

      - name: Build and push (Partner API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: partner/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PARTNER_API }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PARTNER_API }}:v${{github.run_number}}
